export {default as Contact} from './Contact-section/Contact-section'
export {default as Footer} from './Footer-section/Footer-section'
export {default as Hero} from './Hero-section/Hero-section'
export {default as Scroller} from './Scroller-section/Scroller-section'
export {default as Works} from './Works-section/Works-section'
